module Cookstylist
  class Pullrequest
    require "git"

    def initialize(repo, corrector)
      @repo = repo
      @corrector = corrector
      @gh_conn = Cookstylist::Github.instance.connection
    end

    #
    # Open the Cookstyle PR against the repo
    #
    # @return [void]
    #
    def open
      commit_changes

      if Config[:whyrun]
        Log.info "  Would create pull request in repo: #{@repo.name} using branch #{@repo.cookstyle_branch_name} if not in whyrun mode"
      else
        @gh_conn.create_pull_request(@repo.name, @repo.default_branch, @repo.cookstyle_branch_name, commit_title, commit_description)
      end
    end

    def commit_changes
      r = Git.open(@repo.local_path)
      r.config("user.name", "Cookstyle Bot")
      r.config("user.email", "cookbooks@chef.io")

      r.commit_all("#{commit_title}\n#{commit_description}")

      if Config[:whyrun]
        Log.info "  Would push branch #{@repo.cookstyle_branch_name} to the remote if not in whyrun mode"
      else
        r.push("origin", @repo.cookstyle_branch_name)
      end
    end

    def commit_title
      "Cookstyle Bot Auto Corrections with Cookstyle #{@corrector.release}"
    end

    def commit_description
      commit_msg = "This change is automatically generated by the Cookstyle Bot using the latest version of Cookstyle (#{@corrector.release}). Adopting changes suggested by Cookstyle improves cookbook readability, avoids common coding mistakes, and eases upgrades to newer versions of the Chef Infra Client.\n\n"

      @corrector.results_by_cop.each do |cop_name, offenses|
        # build each line's description if it's correctable. We'll join them on their own line later
        file_descriptions = offenses.filter_map do |x|
          "  - **#{x["file_path"]}:#{x["location"]["start_line"]}**: #{x["message"]}" if x["corrected"]
        end

        commit_msg << "#{cop_name}\n#{file_descriptions.join("\n")}\n" unless file_descriptions.empty?
      end

      commit_msg << "\nSigned-off-by: Cookstyle <cookbooks@chef.io>"

      commit_msg
    end
  end
end